### ISSUE TITLE
Getting Started should show dependency injection

### ISSUE THREAD

**Issue by michael-freidgeim-webjet** [aliencube/Microsoft-ADAL-Wrapper#1]
Getting Started  section of readme shows usage of concrete class

```
using (var context = new AuthenticationContextWrapper(authority))
{
  var result = await context.AcquireTokenAsync(resource, credential);
}
```
which makesi it unclear how you can use mock.
It will be good to provide DI example. (Or am I missing something?)

**Comment by justinyoo** [comment]
@michael-freidgeim-webjet The next code snippet shows you how to mock `AuthenticationContextWrapper` using `IAuthenticationContextWrapper`.

For your DI purpose, you can simply apply injecting `IAuthenticationContextWrapper` at `Startup.cs` in your ASP.NET Core app like:

```
services.AddTransient<IAuthenticationContextWrapper>(_ => new AuthenticationContextWrapper(authority));
```

Or you can follow conventions of your preferable IoC container define.

HTH
